# Generated by Django 3.0.9 on 2020-08-18 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gogoedu', '0002_auto_20200818_0656'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer_num', models.IntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gogoedu.Test')),
            ],
        ),
        migrations.CreateModel(
            name='UserWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memoried', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_word',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user_word',
            name='word',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='avatar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='User_test',
        ),
        migrations.DeleteModel(
            name='User_word',
        ),
        migrations.AddField(
            model_name='userword',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userword',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gogoedu.Word'),
        ),
        migrations.AddField(
            model_name='usertest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
